### ISSUE TITLE
关于自动打卡任务的删除

### ISSUE THREAD

**Issue by HotoCocoaco** [Duangdi/fuck-wozaixiaoyuan#1]
我按照使用篇之后做了，突然想自己整一个。可不可以麻烦一下删除我在你的数据库里面的东西？
姓名写了：陈睿
学号写了：1541789503
当然是乱写的

**Comment by Duangdi** [comment]
> 我按照使用篇之后做了，突然想自己整一个。可不可以麻烦一下删除我在你的数据库里面的东西？
> 姓名写了：陈睿
> 学号写了：1541789503
> 当然是乱写的

已帮你删了，你随便写就行了，本来就用来相互学习的。
